services:
  mysql-service:
    image: mysql:8
    container_name: mysql-container
    volumes:
      - mysql-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT__PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - wordpress-network
    restart: always

  wordpress-service:
    image: wordpress:6.5
    container_name: wordpress-container
    volumes:
      - wordpress-volume:/var/www/html
    environment:
      WORDPRESS_DB_HOST: ${MYSQL_HOST}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 8080:80
    networks:
      - wordpress-network
    depends_on: 
      - mysql-service
    restart: always

  phpmyadmin-service:
    image: phpmyadmin:5.2
    container_name: phpmyadmin-container
    environment:
      PMA_HOST: ${MYSQL_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT__PASSWORD}
    ports:
      - 8081:80
    depends_on: 
      - mysql-service
    networks:
      - wordpress-network
    restart: always

volumes:
  mysql-volume:
  wordpress-volume:

networks:
  wordpress-network: